gitpod:
  hostname: gitpod.example.com

  certificatesSecret:
    secretName: proxy-config-certificates
    path: secrets/https-certificates/*

  components:
    workspace:
      template:
        spec:
          dnsConfig: null
          dnsPolicy: ClusterFirst
          # use these values if you would like to configure a specific DNS server:
          # dnsConfig:
          #   nameservers:
          #   - 10.0.0.1
          # dnsPolicy: None

  authProviders:
  - id: "Local GitLab"
    host: "gitlab.example.com"
    protocol: "https"
    type: "GitLab"
    oauth:
      clientId: "a6bdd1eef090b1890c68e5f8370782d05ee2ce8bfb95d9a1e0ed305427f35e10"
      clientSecret: "5464c983c47f6eb2e80dd37de28152de05ea5447d23643f7e71353d9fc3ad1c1"
      callBackUrl: "https://gitpod.example.com/auth/gitlab/callback"
      settingsUrl: "gitlab.example.com/profile/applications"

  installPodSecurityPolicies: true

gitpod_selfhosted:
  variants:
    customCerts: true
